version: 2.1

jobs:
  deploy:
    docker:
      - image: circleci/python:3.7.2-stretch
    steps:
      - checkout
      - run: sudo pip install awscli zappa
      - run:
          name: "Print App Environment Variables"
          command: bash ./.circleci/scripts/print_vars.sh
      - run:
          name: "Install Dependencies"
          command: pipenv install
      - run:
          name: "Deploy coa-forms-api Lambda with Zappa"
          command: bash ./.circleci/scripts/deploy.sh

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy
